version: 2
jobs:
  build:
    working_directory: ~/circleci-example
    parallelism: 1
    machine: true
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      GROUP: anhnguyenkim
      REPO: docker-whale-example

    # docker:
    #   - image: circleci/python:3.5

    steps:
      - checkout
