version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run: echo "Run your code here"
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
