version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.13
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - run:
          name: AWS CLI
          command: |
            aws s3 ls
workflows:
  version: 2
  aws-cli:
    jobs:
      - aws-cli-example:
          context: aws
