version: 2
jobs:
  build:
    docker:
      # using custom image, see .circleci/images/primary/Dockerfile
      - image: circleci/python:3.5-stretch-browsers
      - image: postgres:9.4.1
        name: dbtest
        environment:
          POSTGRES_USER: testdb
          POSTGRES_PASSWORD: testdb
          POSTGRES_DB: testdb
    working_directory: ~/anhnguyen/circleci-example

    environment:
      TEST_RESULTS: /tmp/test-results
      GROUP: anhnguyenkim
      REPO: docker-whale-example

    steps:
      - checkout

      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z dbtest 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgress && exit 1

      - run: mkdir -p $TEST_RESULTS

      - setup_remote_docker

      - run: |
          set -e
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          docker ps


      # - run:
      #     name: Run unit test
      #     environment:
      #       DATABASE_URL: "postgres://testdb@127.0.0.1:5432/testdb?sslmode=disable"
      #     command: ./docker/test/test.sh

      - run:
          name: Build and push Docker image
          command: |
            ./docker/bin/build.sh
            # ./docker/bin/push.sh

      - run:
          name: Test
          command: |
            ./docker/test/test.sh

      - run:
          name: Check
          command: |
            docker images

      # - run:
          # name: Build and push Docker image
          # command: |
          #   TAG="0.1.${CIRCLE_BUILD_NUM}"
          #   docker build -t circleci/cci-demo-docker:$TAG .
          #   docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
          #   docker push circleci/cci-demo-docker:$TAG

      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results:
          path: /tmp/test-results
