version: 2.1
orbs:
  aws-cli: afrase/aws-cli@0.0.2
jobs:
  build:
    working_directory: ~/circleci-example
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          name: AWS CLI
          command: |
            set -e
            aws s3 ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
