FROM concourseglobal/docker-img-django:develop

COPY . /usr/local/src/api-app

WORKDIR /usr/local/src/api-app

# Collect admin's static assets silently
RUN python manage.py collectstatic --noinput > /dev/null 2>&1

# The port that the gunicorn web application is running
EXPOSE 80

ENTRYPOINT ["bin/entrypoint.sh"]

CMD ["bin/dj-gunicorn.sh", "80"]
